const actionsTypesCatalogs = {
    LOADING_SUCCESS_CATALOGS: 'LOADING_SUCCESS_CATALOGS',
    LOAD_SUCCESS_CATALOGS: 'LOAD_SUCCESS_CATALOGS',
    LOAD_FAILURE_CATALOGS: 'LOAD_FAILURE_CATALOGS'
}

export default actionsTypesCatalogs
